// startup.tjs - スタートアップスクリプト
// Copyright (C) 2001, W.Dee  改変・配布は自由です

// このスクリプトは一番最初に実行されるスクリプトです
@if (kirikiriz)
property _dummyProp { getter {} setter (v) {} }
with(Window) {
    &.innerSunken    = &_dummyProp;
    &.showScrollBars = &_dummyProp;
}
Plugins.link("plugin/menu.dll");       // メニューを使わないなら不要
Plugins.link("plugin/KAGParser.dll");  // KAGを使わない(!)なら不要
@endif

Scripts.execStorage("system/Boot.tjs");
